In [1]:
import torch
import numpy as np

### Def Tensor

In [2]:
x = torch.Tensor(3, 4)
print(x)

tensor([[1.2969e+21, 4.5747e-41, 1.2969e+21, 4.5747e-41],
        [1.4013e-45, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [2.6409e+17, 4.5747e-41, 0.0000e+00, 0.0000e+00]])


In [3]:
y = torch.randn(3, 4)
print(y)

tensor([[ 2.6779,  0.3507,  1.8387, -0.9544],
        [-0.2650,  1.5394, -1.1349,  0.7140],
        [-0.5999,  0.8775, -0.4858,  0.7293]])


### Add Tensor

In [4]:
z = x + y
print(z)

tensor([[ 1.2969e+21,  3.5067e-01,  1.2969e+21, -9.5441e-01],
        [-2.6502e-01,  1.5394e+00, -1.1349e+00,  7.1401e-01],
        [ 2.6409e+17,  8.7747e-01, -4.8579e-01,  7.2926e-01]])


In [5]:
j = torch.Tensor(3, 4)
torch.add(x, 20, out=j)
print(j)

tensor([[1.2969e+21, 2.0000e+01, 1.2969e+21, 2.0000e+01],
        [2.0000e+01, 2.0000e+01, 2.0000e+01, 2.0000e+01],
        [2.6409e+17, 2.0000e+01, 2.0000e+01, 2.0000e+01]])


### Compare Tensor

In [6]:
cp = torch.gt(x, y)
print(cp)

tensor([[ True, False,  True,  True],
        [ True, False,  True, False],
        [ True, False,  True, False]])


### Tensor & Numpy

In [7]:
a = x.numpy()
print(a)

[[1.2968734e+21 4.5746790e-41 1.2968734e+21 4.5746790e-41]
 [1.4012985e-45 0.0000000e+00 0.0000000e+00 0.0000000e+00]
 [2.6409472e+17 4.5746790e-41 0.0000000e+00 0.0000000e+00]]


In [8]:
b = np.ones((3, 4))
w = torch.from_numpy(b)
print(w)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


In [9]:
c = np.add(a, 2)
print(c)

[[1.2968734e+21 2.0000000e+00 1.2968734e+21 2.0000000e+00]
 [2.0000000e+00 2.0000000e+00 2.0000000e+00 2.0000000e+00]
 [2.6409472e+17 2.0000000e+00 2.0000000e+00 2.0000000e+00]]


### Squeeze

In [10]:
x = torch.Tensor(2,1,1,2)
y = torch.squeeze(x)
print(x.size(), y.size())
print(x, '\n', y)

torch.Size([2, 1, 1, 2]) torch.Size([2, 2])
tensor([[[[0., 0.]]],


        [[[0., 0.]]]]) 
 tensor([[0., 0.],
        [0., 0.]])
